import React, { useEffect, useState } from "react";
// NextJs import
import Head from "next/head";
import Image from 'next/image';
// Components imports
import SideBar from "Components/SideBar/SideBar";
import Header from "../header/Header";
// Redux imports
import {add, remove} from "Redux/reduxSlices/userDetailSlice";
import { useSelector, useDispatch } from 'react-redux';

export default function DashboardLayout(props) {
  //const userDetailsDispatch = useDispatch();
  //const leadsDataDispatch = useDispatch();
  const userDetails = useSelector((state) => state.userDetails.userDetails);

  //useEffect(() => {
  //  if(userDetails.email?.length === 0) {
  //    BackendService.getUser().then((res) => {
  //      console.log(res.data);
  //      userDetailsDispatch(add({...res.data}));
  //    }).catch(err => console.log(err))
  //  }
  //}, []);

  return (
    <>
      <Head>
        <title>Leads Management App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="favicon.ico" />
      </Head>

      <div className="flex h-screen overflow-hidden">

      {/* Sidebar */}
      <SideBar />

      {/* Content area */}
      <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden bg-slate-100">

        {/*  Site header */}
         <Header user={props.user} proPicStatus={userDetails?.profilepic}/> 

        <main className='bg-slate-100'>
          <div className="px-4 sm:px-6 lg:px-8 py-4 w-full max-w-9xl mx-auto">
             {props.children}
          </div>
          </main>
        </div>
      </div>
    </>
  );
}